version: '3.8'
services:
  frontend:
    image: frontend
    build: ./frontend
    ports:
      - ${FRONTEND_PORT:?}:80

  mariadb:
    image: mariadb:11.1
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:?}
      MYSQL_DATABASE: ${DATABASE_NAME:?}
      MYSQL_USER: ${DATABASE_USER:?}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:?}
    # DO NOT CHANGE
    ports:
      - 3306:3306
    volumes:
    # remove if the database should not be seeded
      - "./data/mariadb/sql:/docker-entrypoint-initdb.d"
    restart: always

  backend:
    image: backend
    build:
      context: ./backend
    depends_on:
      - mariadb
    restart: unless-stopped
    ports:
      - ${BACKEND_PORT:?}:${BACKEND_PORT}
    env_file:
      - .env